//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Gamasis.ProjectManagement.WsUser {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsersSoap", Namespace="http://gamasis.com.mx/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GRes))]
    public partial class Users : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginAlaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginGamasisOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginBioMatcherOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Users() {
            this.Url = global::Gamasis.ProjectManagement.Properties.Settings.Default.Gamasis_ProjectManagement_WsUser_Users;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LoginAlaveCompletedEventHandler LoginAlaveCompleted;
        
        /// <remarks/>
        public event LoginGamasisCompletedEventHandler LoginGamasisCompleted;
        
        /// <remarks/>
        public event LoginBioMatcherCompletedEventHandler LoginBioMatcherCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gamasis.com.mx/Login", RequestNamespace="http://gamasis.com.mx/", ResponseNamespace="http://gamasis.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginUser Login(string Username, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        Username,
                        Password});
            return ((LoginUser)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password) {
            this.LoginAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Username,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gamasis.com.mx/LoginAlave", RequestNamespace="http://gamasis.com.mx/", ResponseNamespace="http://gamasis.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginUser LoginAlave(string Username, string Password) {
            object[] results = this.Invoke("LoginAlave", new object[] {
                        Username,
                        Password});
            return ((LoginUser)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAlaveAsync(string Username, string Password) {
            this.LoginAlaveAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginAlaveAsync(string Username, string Password, object userState) {
            if ((this.LoginAlaveOperationCompleted == null)) {
                this.LoginAlaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAlaveOperationCompleted);
            }
            this.InvokeAsync("LoginAlave", new object[] {
                        Username,
                        Password}, this.LoginAlaveOperationCompleted, userState);
        }
        
        private void OnLoginAlaveOperationCompleted(object arg) {
            if ((this.LoginAlaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAlaveCompleted(this, new LoginAlaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gamasis.com.mx/LoginGamasis", RequestNamespace="http://gamasis.com.mx/", ResponseNamespace="http://gamasis.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginUser LoginGamasis(string Username, string Password) {
            object[] results = this.Invoke("LoginGamasis", new object[] {
                        Username,
                        Password});
            return ((LoginUser)(results[0]));
        }
        
        /// <remarks/>
        public void LoginGamasisAsync(string Username, string Password) {
            this.LoginGamasisAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginGamasisAsync(string Username, string Password, object userState) {
            if ((this.LoginGamasisOperationCompleted == null)) {
                this.LoginGamasisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginGamasisOperationCompleted);
            }
            this.InvokeAsync("LoginGamasis", new object[] {
                        Username,
                        Password}, this.LoginGamasisOperationCompleted, userState);
        }
        
        private void OnLoginGamasisOperationCompleted(object arg) {
            if ((this.LoginGamasisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginGamasisCompleted(this, new LoginGamasisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gamasis.com.mx/LoginBioMatcher", RequestNamespace="http://gamasis.com.mx/", ResponseNamespace="http://gamasis.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginUser LoginBioMatcher(string Username, string Password) {
            object[] results = this.Invoke("LoginBioMatcher", new object[] {
                        Username,
                        Password});
            return ((LoginUser)(results[0]));
        }
        
        /// <remarks/>
        public void LoginBioMatcherAsync(string Username, string Password) {
            this.LoginBioMatcherAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginBioMatcherAsync(string Username, string Password, object userState) {
            if ((this.LoginBioMatcherOperationCompleted == null)) {
                this.LoginBioMatcherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginBioMatcherOperationCompleted);
            }
            this.InvokeAsync("LoginBioMatcher", new object[] {
                        Username,
                        Password}, this.LoginBioMatcherOperationCompleted, userState);
        }
        
        private void OnLoginBioMatcherOperationCompleted(object arg) {
            if ((this.LoginBioMatcherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginBioMatcherCompleted(this, new LoginBioMatcherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gamasis.com.mx/")]
    public partial class LoginUser : GRes {
        
        private User userDataField;
        
        /// <remarks/>
        public User UserData {
            get {
                return this.userDataField;
            }
            set {
                this.userDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gamasis.com.mx/")]
    public partial class User {
        
        private int idField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string secondLastnameField;
        
        private string emailField;
        
        private string profileField;
        
        private bool activeField;
        
        private string roleField;
        
        private int genericRoleField;
        
        private string fromField;
        
        private string phoneField;
        
        private string additionalDataField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string SecondLastname {
            get {
                return this.secondLastnameField;
            }
            set {
                this.secondLastnameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int GenericRole {
            get {
                return this.genericRoleField;
            }
            set {
                this.genericRoleField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gamasis.com.mx/")]
    public partial class GRes {
        
        private bool okField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public bool Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginAlaveCompletedEventHandler(object sender, LoginAlaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAlaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAlaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginGamasisCompletedEventHandler(object sender, LoginGamasisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginGamasisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginGamasisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginBioMatcherCompletedEventHandler(object sender, LoginBioMatcherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginBioMatcherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginBioMatcherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginUser)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591